name: assets_generator
description: help flutter developer to quickly auto generate assets configs in yaml.
version: 2.0.0
homepage: https://github.com/fluttercandies/assets_generator
author: zmtzawqlp <zmtzawqlp@live.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  build_runner_core: any
  io: any
  path: any
  args: any
  meta: ^1.2.3
  dart_style: any


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

executables:
  agen: assets_generator


# pub global activate --source path ./
# pub global activate assets_generator