name: assets_generator
description: The flutter tool to generate assets‘s configs(yaml) and consts automatically for single project and multiple modules.
version: 2.0.1
homepage: https://github.com/fluttercandies/assets_generator

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  args: ^1.6.0
  build_runner_core: ^6.0.3
  dart_style: ^1.3.6
  io: ^0.3.3
  meta: ^1.1.8
  path: ^1.0.0
  yaml: ^2.0.0


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

executables:
  agen: assets_generator


# pub global activate --source path ./
# pub global activate assets_generator