name: gp_assets_generator
description: The flutter tool to generate assets‘s configs(yaml) and consts automatically for single project and multiple modules.
version: 1.0.2
homepage: https://github.com/toannmdev/gp_assets_generator.git

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.2.0
  build_runner_core: ^7.1.0
  dart_style: ^2.0.3
  io: ^1.0.3
  meta: ^1.7.0
  path: ^1.8.0
  source_span: ^1.8.1
  yaml: ^3.1.0
  mime: ^1.0.2

dev_dependencies:
  pedantic: ^1.11.1

executables:
  gp_agen: gp_assets_generator


# dart pub global activate --source path ./
# dart pub global activate gp_assets_generator