// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'package:easy_sds_config/easy_sds_config.dart';

class Assets {
  const Assets._();
  static const String assets_dd_txt = 'assets/dd.txt';

  /// {@macro assets_generator.assets_images_flutter_candies_logo_png.preview}
  static const String assets_images_flutter_candies_logo_png =
      'assets/images/flutter_candies_logo.png';

  static const String assets_test_txt = 'assets/test.txt';
}

final List<String> assetsArray = <String>[
  Assets.assets_dd_txt,

  /// {@macro assets_generator.assets_images_flutter_candies_logo_png.preview}
  Assets.assets_images_flutter_candies_logo_png,
  Assets.assets_test_txt,
];
