// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'package:easy_sds_config/easy_sds_config.dart';

class Assets {
  const Assets._();
  static const String package = 'module_a';

  static bool isFromModules = ConfigAssets.isFromModules;

  static String get assets_abc_txt =>
      '${isFromModules ? "packages/module_a/" : ""}assets/abc.txt';

  /// {@macro assets_generator.assets_images_flutter_candies_logo_png.preview}
  static String get assets_images_flutter_candies_logo_png =>
      '${isFromModules ? "packages/module_a/" : ""}assets/images/flutter_candies_logo.png';

  /// {@macro assets_generator.assets_images_image_png.preview}
  static String get assets_images_image_png =>
      '${isFromModules ? "packages/module_a/" : ""}assets/images/image.png';

  static String get assets_images_test_txt =>
      '${isFromModules ? "packages/module_a/" : ""}assets/images/test.txt';

  static String get assets_xxx_md =>
      '${isFromModules ? "packages/module_a/" : ""}assets/xxx.md';
}

final List<String> assetsArray = <String>[
  Assets.assets_abc_txt,

  /// {@macro assets_generator.assets_images_flutter_candies_logo_png.preview}
  Assets.assets_images_flutter_candies_logo_png,

  /// {@macro assets_generator.assets_images_image_png.preview}
  Assets.assets_images_image_png,
  Assets.assets_images_test_txt,
  Assets.assets_xxx_md,
];
