// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'module_a';

  static const String assets_abc_txt = 'assets/abc.txt';

  /// {@macro assets_generator.assets_images_flutter_candies_logo_png.preview}
  static const String assets_images_flutter_candies_logo_png =
      'assets/images/flutter_candies_logo.png';

  /// {@macro assets_generator.assets_images_image_png.preview}
  static const String assets_images_image_png = 'assets/images/image.png';

  static const String assets_images_test_txt = 'assets/images/test.txt';

  static const String assets_xxx_md = 'assets/xxx.md';
}

final List<String> assetsArray = <String>[
  Assets.assets_abc_txt,

  /// {@macro assets_generator.assets_images_flutter_candies_logo_png.preview}
  Assets.assets_images_flutter_candies_logo_png,

  /// {@macro assets_generator.assets_images_image_png.preview}
  Assets.assets_images_image_png,
  Assets.assets_images_test_txt,
  Assets.assets_xxx_md,
];
